PSME-38: criando todos os metodos da tabela do banco do usuario.
nicolasgfe/Selfie.me pull request #14
Opened 2024-04-05 01:26 UTC by nicolasgfe

2024-04-05 17:48 UTC, Gmod9K requested changes
IsNotEmpty() faltando na coluna de sobrenome no dto

2024-04-05 17:48 UTC, Gmod9K commented on backend/src/dto/usuario/index.ts
> +
Colocar IsNotEmpty() aqui.

2024-04-05 18:28 UTC, nicolasgfe commented on backend/src/dto/usuario/index.ts
> +
Resolvido

2024-04-06 11:15 UTC, Gmod9K approved these changes
Agora sim

2024-04-06 11:40 UTC, merged