Pmse 42
nicolasgfe/Selfie.me pull request #17
Opened 2024-04-06 13:59 UTC by HelitonCalgaroto

2024-04-08 22:25 UTC, nicolasgfe requested changes

2024-04-08 22:25 UTC, nicolasgfe commented on backend/src/controllers/licenca/index.ts
> +import { LicencaService } from 'src/service/licenca';
Deve ser exportado e importado do arquivo index.ts

2024-04-08 22:25 UTC, nicolasgfe commented on backend/src/module/licenca/index.ts
> +import { LicencaService } from 'src/service/licenca';
Deve ser exportado e importado do arquivo index.ts

2024-04-08 22:25 UTC, nicolasgfe commented on backend/src/repository/licenca/index.ts
> +import { Licenca } from 'src/entity';
Deve ser exportado e importado do arquivo index.ts

2024-04-08 22:25 UTC, nicolasgfe commented on backend/src/service/licenca/index.ts
> +import { CreateLicencaDto } from 'src/dto/licenca';
Deve ser exportado e importado do arquivo index.ts

2024-04-08 22:25 UTC, nicolasgfe commented on backend/src/service/licenca/index.ts
> +import { LicencaRepository } from 'src/repository/licenca';
Deve ser exportado e importado do arquivo index.ts

2024-04-08 23:25 UTC, nicolasgfe requested changes

2024-04-08 23:25 UTC, nicolasgfe commented on backend/src/module/licenca/index.ts
> +import { LicencaController } from 'src/controllers/licenca';
Resolver import

2024-04-09 00:19 UTC, Gmod9K approved these changes

2024-04-14 14:16 UTC, merged