PSME 44: Criando estruturas para tabela comentario.
nicolasgfe/Selfie.me pull request #20
Opened 2024-04-06 14:25 UTC by HelitonCalgaroto

2024-04-08 23:12 UTC, nicolasgfe requested changes

2024-04-08 23:12 UTC, nicolasgfe commented on backend/src/controllers/licenca/index.ts
> +import { LicencaService } from 'src/service/licenca';
O LicencaService deve ser adicionado no arquivo index.ts da pasta service. para conseguir importar de outra maneira

2024-04-08 23:12 UTC, nicolasgfe commented on backend/src/dto/comentario/index.ts
> +    idSubComentario: number;
Nome do campo na modelagem é idComentario

2024-04-08 23:12 UTC, nicolasgfe commented on backend/src/entity/comentario/index.ts
> +    @JoinColumn({name: 'idSubComentario'})
Nome do campo é idComentario

2024-04-08 23:12 UTC, nicolasgfe commented on backend/src/entity/index.ts
> +export * from './comentario';
Deve ser exportado a licenca tbm

2024-04-08 23:12 UTC, nicolasgfe commented on backend/src/module/licenca/index.ts
> +import { LicencaService } from 'src/service/licenca';
deve ser adicionado no arquivo index.ts da pasta service. para conseguir importar de outra maneira

2024-04-08 23:12 UTC, nicolasgfe commented on backend/src/repository/licenca/index.ts
> +import { CreateLicencaDto } from 'src/dto/licenca';
deve ser adicionado no arquivo index.ts da pasta service. para conseguir importar de outra maneira

2024-04-08 23:12 UTC, nicolasgfe commented on backend/src/service/licenca/index.ts
> +import { LicencaRepository } from 'src/repository/licenca';
deve ser adicionado no arquivo index.ts da pasta service. para conseguir importar de outra maneira

2024-04-08 23:23 UTC, HelitonCalgaroto commented on backend/src/dto/comentario/index.ts
> +    idSubComentario: number;
Mas esse seria uma réplica do comentário, ou seja, um comentário sobre o comentário.. então o nome fica confuso se ficar igual

2024-04-08 23:24 UTC, HelitonCalgaroto commented on backend/src/entity/comentario/index.ts
> +    @JoinColumn({name: 'idSubComentario'})
Réplica do comentário

2024-04-08 23:24 UTC, HelitonCalgaroto commented on backend/src/entity/index.ts
> +export * from './comentario';
essa alteração vou fazer na branch da licença

2024-04-09 00:15 UTC, Gmod9K requested changes
Mudanças já requisitada em review prévia.

2024-04-14 14:35 UTC, merged