Psme 41
nicolasgfe/Selfie.me pull request #21
Opened 2024-04-06 22:03 UTC by nicolasgfe

2024-04-08 23:51 UTC, HelitonCalgaroto requested changes

2024-04-08 23:51 UTC, HelitonCalgaroto commented on backend/src/controllers/publicacao/index.ts
> +import { PublicacaoService } from 'src/service/publicacao';
Importar o Service do index.ts

2024-04-08 23:51 UTC, HelitonCalgaroto commented on backend/src/service/publicacao/index.ts
> +import { PublicacaoRepository } from 'src/repository/publicacao';
Importar o repository do index.ts

2024-04-09 00:09 UTC, Gmod9K requested changes
Mudanças já requisitada em review prévia.

2024-04-14 14:30 UTC, merged