PSME - Criacao de Midia
nicolasgfe/Selfie.me pull request #22
Opened 2024-04-06 22:53 UTC by nicolasgfe

2024-04-08 23:49 UTC, HelitonCalgaroto requested changes

2024-04-08 23:49 UTC, HelitonCalgaroto commented on backend/src/app.module.ts
> +import { MidiaModule } from './module';
Importar MidiaModule na mesma linha dos demais.

2024-04-08 23:49 UTC, HelitonCalgaroto commented on backend/src/controllers/publicacao/index.ts
> +import { PublicacaoService } from 'src/service/publicacao';
Importar o Service do index.ts

2024-04-08 23:49 UTC, HelitonCalgaroto commented on backend/src/service/publicacao/index.ts
> +import { PublicacaoRepository } from 'src/repository/publicacao';
Importar o Repository do Index.ts

2024-04-09 00:01 UTC, Gmod9K commented on backend/src/app.module.ts
> +import { MidiaModule } from './module';
Importar MidiaModule na mesma linha dos demais.

2024-04-09 00:03 UTC, Gmod9K requested changes
Mudanças já requisitadas em revisão prévia.

2024-04-14 14:30 UTC, merged