US-18: Criação de tela "Produto"
nicolasgfe/Selfie.me pull request #24
Opened 2024-04-08 22:33 UTC by LeonardoHartmann

2024-04-08 23:43 UTC, nicolasgfe requested changes

2024-04-08 23:43 UTC, nicolasgfe commented on frontend/package.json
> +  "name": "test_job",
O que significa ''test_job''
Acredito que seria interessante adicionar frontend mesmo ou o nome do servico da aplicacao

2024-04-08 23:43 UTC, nicolasgfe commented on frontend/src/assets/index.ts
> +
Remover linha. Para manter o codigo limpo e organizado

2024-04-08 23:43 UTC, nicolasgfe commented on frontend/src/pages/home/home.tsx
> +            flexDirection="column">
Como uma boa pratica, adicione as propriedades do emento, em linhas separadas da abertura e fechamento do elemento
exemplo:
<Box
    backgroudcolor="#fffff"
    w={""}
>

2024-04-08 23:43 UTC, nicolasgfe commented on frontend/src/pages/home/home.tsx
> +            flexDirection="revert">
adicione as propriedades do emento, em linhas separadas da abertura e fechamento do elemento

2024-04-08 23:43 UTC, nicolasgfe commented on frontend/src/pages/home/home.tsx
> +                <Text color={"#ffffff"}>
Correto. Quando tiver menas propriedades adicionar tudo em um linha somente.

2024-04-08 23:43 UTC, nicolasgfe commented on frontend/src/pages/liked/liked.tsx
> +            flexDirection="column">
adicione as propriedades do emento, em linhas separadas da abertura e fechamento do elemento

2024-04-08 23:43 UTC, nicolasgfe commented on frontend/src/pages/liked/liked.tsx
> +            flexDirection="revert">
adicione as propriedades do emento, em linhas separadas da abertura e fechamento do elemento

2024-04-08 23:43 UTC, nicolasgfe commented on frontend/src/pages/product/index.ts
> +
Remover linha

2024-04-08 23:43 UTC, nicolasgfe commented on frontend/src/pages/product/product.tsx
> +        <Box display={"flex"} alignItems={'center'} flexDirection={'column'} w={'100vw'} h={'100vh'}>
Fragmentar linha grande com as propriedades em linhas individuais para os mesmos.

2024-04-08 23:43 UTC, nicolasgfe commented on frontend/src/pages/product/product.tsx
> +            {/*Head */}
Remover linha e elemento comentado

2024-04-08 23:43 UTC, nicolasgfe commented on frontend/src/pages/product/product.tsx
> +                height="100px">
adicione as propriedades do emento, em linhas separadas da abertura e fechamento do elemento

2024-04-08 23:43 UTC, nicolasgfe commented on frontend/src/pages/product/product.tsx
> +
Remover linhas em branco

2024-04-08 23:43 UTC, nicolasgfe commented on frontend/src/pages/product/product.tsx
> +
Remover linhas em branco

2024-04-08 23:43 UTC, nicolasgfe commented on frontend/src/pages/product/product.tsx
> +            {/*Body */}
Remover comentario

2024-04-08 23:43 UTC, nicolasgfe commented on frontend/src/pages/product/product.tsx
> +
remover linha

2024-04-08 23:43 UTC, nicolasgfe commented on frontend/src/pages/product/product.tsx
> +
Remover linhas

2024-04-08 23:43 UTC, nicolasgfe commented on frontend/src/pages/product/product.tsx
> +
Remover linhas

2024-04-08 23:44 UTC, nicolasgfe requested changes

2024-04-08 23:44 UTC, nicolasgfe commented on frontend/src/reportWebVitals.ts
> +export default reportWebVitals;
Remover arquivo

2024-04-08 23:47 UTC, Jabutiranha approved these changes

2024-04-09 01:21 UTC, nicolasgfe approved these changes

2024-04-09 01:25 UTC, LeonardoHartmann commented
Corrigido todos os problemas

2024-04-09 01:25 UTC, Jabutiranha requested changes

2024-04-09 01:25 UTC, Jabutiranha commented on frontend/src/pages/product/product.tsx
> +        <Box display={"flex"} alignItems={'center'} flexDirection={'column'} w={'100vw'} h={'100vh'}>
Não realizou as correções solicitadas pelo @nicolasgfe , pois ainda continua com linha grande

2024-04-09 01:37 UTC, merged